version: "3.8"

services:
  postgres-db:
    image: postgres:13
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

    # Command ini bikin DB kedua (untuk Airflow) otomatis saat startup
    command: >
      sh -c "docker-entrypoint.sh postgres &
      sleep 10;
      psql -U ${DB_USER} -d ${DB_NAME} -c \"CREATE DATABASE ${AIRFLOW_DB_NAME};\" || true;
      wait"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - airflow_network

  airflow:
    build:
      context: ./airflow
    container_name: airflow_container
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      #metadata airflow
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@postgres-db:5432/${AIRFLOW_DB_NAME}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False

      #airflow user and pwd
      - AIRFLOW_USER=${AIRFLOW_USER}
      - AIRFLOW_PASSWORD=${AIRFLOW_PASSWORD}

      #postgre
      - DB_HOST=postgres-db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"

    command: >
      bash -c "pip install --no-cache-dir -r /requirements.txt && 
               airflow db migrate &&
               airflow users create \
               --username \"$${AIRFLOW_USER}\" \
               --password \"$${AIRFLOW_PASSWORD}\" \
               --firstname Admin \
               --lastname User \
               --role Admin \
               --email admin@example.com || true &&
               airflow standalone"
    networks:
      - airflow_network

networks:
  airflow_network:
    driver: bridge

volumes:
  postgres_data:
